package kernel

// --- Classroom IDs (generated by manifesto) ---

type ClassroomID string

func NewClassroomID(id string) ClassroomID { return ClassroomID(id) }
func (id ClassroomID) String() string              { return string(id) }
func (id ClassroomID) IsEmpty() bool               { return string(id) == "" }

// --- Enrollment IDs (generated by manifesto) ---

type EnrollmentID string

func NewEnrollmentID(id string) EnrollmentID { return EnrollmentID(id) }
func (id EnrollmentID) String() string              { return string(id) }
func (id EnrollmentID) IsEmpty() bool               { return string(id) == "" }

// --- Team IDs (generated by manifesto) ---

type TeamID string

func NewTeamID(id string) TeamID { return TeamID(id) }
func (id TeamID) String() string              { return string(id) }
func (id TeamID) IsEmpty() bool               { return string(id) == "" }

// --- Reason IDs (generated by manifesto) ---

type ReasonID string

func NewReasonID(id string) ReasonID { return ReasonID(id) }
func (id ReasonID) String() string              { return string(id) }
func (id ReasonID) IsEmpty() bool               { return string(id) == "" }

// --- Benefit IDs (generated by manifesto) ---

type BenefitID string

func NewBenefitID(id string) BenefitID { return BenefitID(id) }
func (id BenefitID) String() string              { return string(id) }
func (id BenefitID) IsEmpty() bool               { return string(id) == "" }

// --- Medal IDs (generated by manifesto) ---

type MedalID string

func NewMedalID(id string) MedalID { return MedalID(id) }
func (id MedalID) String() string              { return string(id) }
func (id MedalID) IsEmpty() bool               { return string(id) == "" }

// --- Ledger IDs (generated by manifesto) ---

type LedgerID string

func NewLedgerID(id string) LedgerID { return LedgerID(id) }
func (id LedgerID) String() string              { return string(id) }
func (id LedgerID) IsEmpty() bool               { return string(id) == "" }
